-- return {
--   "Davidyz/VectorCode",
--   version = "*", -- optional, depending on whether you're on nightly or release
--   dependencies = { "nvim-lua/plenary.nvim" },
--   cmd = "VectorCode", -- if you're lazy-loading VectorCode
--   enable = false, -- false will disable the plugin
-- }
